services:
  db:
    image: 'postgres:16.3-alpine3.20'
    ports:
      - 9111:5432
    environment:
      POSTGRES_USER: myapp
      POSTGRES_PASSWORD: mypassword
    volumes:
      - ./data/pg:/var/lib/postgresql/data
  redis:
    image: redis:7.2.5-alpine3.20
    ports:
      - 6379:6379
    volumes:
      - ./redis:/data
